name = "Carlos Mendible"
avatar = "/assets/img/about_me.jpg"
bio = "Father | Husband | Senior Cloud Solution Architect | Former Azure & Developer Technologies MVP | Opinions are my own"
company = "Microsoft"
location = "Madrid. Spain"