name = "Carlos Mendible"
avatar = "/assets/img/me_redmond.jpg"
bio = "Father | Husband | Principal Cloud Solution Architect | Former Azure & Developer Technologies MVP | Opinions are my own"
company = "Microsoft"
location = "Madrid. Spain"
