baseURL = "https://carlos.mendible.com/"
title = "Code it Yourself..."
copyright = "Copyright: 2009-{year} - Carlos Mendible. All Rights Reserved."
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
disableLanguages = ["de", "fr", "pl", "ru", "uz", "zh-cn", "zh-hk" ,"zh-tw"] 
paginate = 5
enableRobotsTXT = true
disqusShortname = "codeityourself"
googleAnalytics = "UA-11243417-1"
enableEmoji = true
pygmentsUseClasses = true

canonifyurls = true

[permalinks]
  posts = "/:year/:month/:day/:title/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[build]
  writeStats = true
  