poweredBy = false
logo = false
titleCase = false
palettes = []

[codeBlock]
  maxLines = 120

[search]
  paginate = 5 # Pagination. Default to 10.
  # resultContentWordCount = 240 # The maximum word count of result content for displaying.
  # Fuse.js options. See https://fusejs.io/api/options.html.
  [search.fuse]
    # ignoreLocation = true
    # location = 0
    # isCaseSensitive = false
    minMatchCharLength = 3
    threshold = 0.6
    distance = 500
    # useExtendedSearch = true
