github = "cmendible"
linkedin = "carlosmendible"
twitter = "cmendibl3"
reddit = "cmendibl3"
dockerhub = "cmendibl3"
youtube = "UCzLtSg6AfN7RWN3MdvRw7Dw"
stackoverflow = "332127"
telegram = "cmendibl3"
instagram = "cmendibl3"
keybase = "cmendibl3"
devto = "cmendibl3"
