github = "cmendible"
linkedin = "carlosmendible"
twitter = "cmendibl3"
reddit = "cmendibl3"
youtube = "channel/UCzLtSg6AfN7RWN3MdvRw7Dw"
stackoverflow = "users/332127"
instagram = "cmendibl3"
keybase = "cmendibl3"
devto = "cmendibl3"