---
title: Code it Yourself...
email: carlos@mendible.com
description: A blog on Microsoft Azure and .NET by Carlos Mendible
baseurl: "" # the subpath of your site, e.g. /blog
url: https://carlos.mendible.com
permalink: :year/:month/:day/:title/
author: Carlos Mendible
github: https://github.com/cmendible

enableTags: true
tagarray: []

social:
  - icon: fa-twitter
    link: "https://twitter.com/cmendibl3"
  - icon: fa-linkedin
    link: "https://www.linkedin.com/in/carlosmendible"
  - icon: fa-github
    link: "https://github.com/cmendible"

share:
  twitter_username: cmendibl3

urls:
  - text: About Me
    url: /about/
  - text: About My Dad
    url: /my-dads-profile/
  - text: Posts by Category
    url: /category/dotnetcore/
  - text: RSS Feed
    url: /feed.xml

# twitter_username: cmendibl3
# github_username: cmendible

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jekyll-sitemap
  - jekyll-crosspost-to-medium

disqus_shortname: codeityourself
google_analytics: UA-11243417-1
avatar_url: /static/img/avatar.jpg

paginate: 20
per_page: 20
paginate_path: "/page/:num/"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

jekyll-crosspost_to_medium:
  enabled: true
  status: draft
