name: github pages

on:
  push:
    branches:
      - hugo

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.3.2
        with:
          hugo-version: "latest"

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir

      - name: Feed Fix
        run: cp ./public/posts/feed.xml ./public/feed.xml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.3.2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: main
          PUBLISH_DIR: ./public
