name: github pages

on:
  push:
    branches:
      - hugo

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@hugo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.0
        with:
          hugo-version: "0.58.3"

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir

      - name: Feed Fix
        run: cp ./public/posts/feed.xml ./public/feed.xml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.github }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
